### ISSUE TITLE
Avoid squash merging for better git history

### ISSUE THREAD

**Issue by davidyuk** [aeternity/aepp-calldata-js#75]
For example, it would allow going directly via `git blame` to a specific commit merged in #70 instead of the whole PR cc: @dincho

**Comment by dincho** [comment]
I rarely see carefully crafted commit sets as in #70, developers are super lazy and do a lot of junk, non-sense, non-atomic commits. I even prefer single PR commits, if you think the history would benefit by multiple commits, feel free to split a feature in multiple PRs.

**Comment by davidyuk** [comment]
The squash merging strategy is more tolerant to dirty commits, making good ones less useful. The default one encourages crafting good commits and in the end makes it obvious for developers why to do so.

In default merging strategy, good commits just increase the probability that you will work with it through `git blame` and make it easier to point to specific change. Also, it preserves the context of change, so finding a bad commit you can switch to the nearest merge commit viewing the whole set of changes (a PR). Nobody read commits in history one by one, so preserving easier access to good commits for me is more important than general good-looking of history.

**Comment by dincho** [comment]
I do read commits in mainline branches one by one. I also insist every mainline commit to be deployable/releasable without any changes (a.k.a golden master), which most of the time is not true for a given set of PR commits, because of their order in example.

I'm not saying your points are not valid, I would love to work with someone that could craft the commits and keep the mainline commits atomic. However, as I wrote before that's far from the reality, thus squash.

As I also mentioned, separate PR's workaround the limitation of squashing, and encourage small, limited scope PR's which is something that I also prefer to work with.
